entryPoints:
  # http redirect to https
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  # https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  mqtts:
    address: ":8883"
  mqtt:
    address: ":1883"

# Letsencrypt TLS
certificatesResolvers:
  letsencrypt:
    acme:
      # Change to your email
      email: your@mail.com
      storage: /etc/traefik/acme/acme.json
      tlsChallenge: {}
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    network: traefik
    endpoint: "unix:///var/run/docker.sock"
    # Change to your domain
    defaultRule: Host(`your.domain`)
    watch: true
    swarmMode: true

